### ISSUE TITLE
Missing `c.libs` break static linking

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/opengl-meta#3]
The current implementation is not setting `c.libs` (which is what's used instead of interface-only `c.export.libs`) when a static variant of the libraries is linked (you can reproduce the problem by building examples with `config.bin.lib=static`).

In other words, this:

```
lib{opengl-gl}:
{
    c.export.libs = $opengl_gl_libs
}
```

Should be:

```
lib{opengl-gl}:
{
    c.libs = $opengl_gl_libs
    c.export.libs = $opengl_gl_libs
}
```

(And equivalent for other libraries.)

BTW, `libpthread-meta`, which I believe is the inspiration for this library, correctly sets `c.libs`.

**Comment by Rookfighter** [comment]
Sure, I'll fix this :+1: Could you give me a bit more insights what the difference between `c.libs` and `c.export.libs` is? I do not really get why linking in the static case would fail. And is this issue also true for all other packages (that `c.libs` is required for static linking)? Just asking because I have never used the construct before and `bdep new` does not seem to produce this either:

```
lib{opengl-gl}:
{
    c.libs = $opengl_gl_libs
    c.export.libs = $opengl_gl_libs
}
```

**Comment by boris-kolpackov** [comment]
Some relevant replies from the slack channel that hopefully clarifies this:

> It's also helpful to understand the underlying semantics of static vs shared libraries, in particular, the asymmetry that stems from the fact that for static libraries you need to link both interface and implementation dependencies (which is prerequisites plus `c.libs`) while for shared -- only interface (which is `c.export.libs`).

> Also, the current semantics is quite intuitive for binful (non-header-only) libraries where if you forget to list a library in `c.libs` you will get a linker error. Where things become less intuitive are binless libraries which still link binful libraries, which is probably not a very common case.

Plus the relevant section in the manual: https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-lib

**Comment by Rookfighter** [comment]
After giving it some thought it makes sense when linking statically to pass the link-arguments to consumers exactly the same way as they were specified in the buildfile for compiling the consumed target. So is it correct that build2 simply passes the `c.libs` arguments (and cxx / cc) instead of the `c.export.libs` in the static linkage case?

Do also I understand correctly, that the passed link-arguments are merged from the `c.libs` on builfile scope, the `c.libs` in the target specific scope and the not exported lib prerequisites?
For example:

```
lib{hello}: $intf_libs $impl_libs
c.libs += -lfoo -lbar

lib{hello}
{
   c.libs = -lworld
}
```

So the link-arguments passed to consumers would be `$intf_libs $impl_libs -lfoo -lbar -lworld` (keeping the internals of `$intf_libs $impl_libs` abstract)?

Following these thoughts it now makes sense why I never had to take care of this, because typically I have to specify the internal link-arguments correctly to even compile my binful library. And build2 takes care of forwarding these in the static case automatically :+1:

**Comment by boris-kolpackov** [comment]
> After giving it some thought it makes sense when linking statically to pass the link-arguments to consumers exactly the same way as they were specified in the buildfile for compiling the consumed target. So is it correct that build2 simply passes the `c.libs` arguments (and cxx / cc) instead of the `c.export.libs` in the static linkage case?

Yes, per your first sentence, for static linking we pass `c.libs` (and prerequsites) instead of `c.export.libs`.

> Do also I understand correctly, that the passed link-arguments are merged from the `c.libs` on builfile scope, the `c.libs` in the target specific scope and the not exported lib prerequisites?

No, this is standard variable lookup starting from the target being linked: https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-dirs-scopes

In your example, you set it (`=`, not `+=`) on target, so that's the only value (`-lworld`) you will get when linking `lib{hello}`.

**Comment by Rookfighter** [comment]
> In your example, you set it (=, not +=) on target, so that's the only value (-lworld) you will get when linking lib{hello}.

Right, I didn't think about that. Got it, thanks :+1:
